version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nuxt_spa
      MYSQL_USER: user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  api:
    stdin_open: true
    tty: true
    build:
      context: ./practice_nuxt_spa_api
      args:
        WORKDIR: $WORKDIR
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
      APP_URL: "http://localhost:$API_PORT"
    volumes:
      - ./practice_nuxt_spa_api:/$WORKDIR
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  front:
    build:
      context: ./practice_nuxt_spa_front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://api:$API_PORT"
        API_URL_BROWSER: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - ./practice_nuxt_spa_front:/$WORKDIR
    depends_on:
      - api
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
